name: WorldShaper
version: @version@
main: net.codedstingray.worldshaper.spigot.WorldShaperSpigot
api-version: 1.13
authors: [CodedStingray]
description: WorldShaper is a map editing plugin designed to empower worldbuilders and terraformers relizing their artistic vision in Minecraft.
website: worldshaper.codedstingray.net
commands:
  wands:
    description: Gives you all WorldShaper wands
    usage: /wands
  wand:
    description: Gives you the requested WorldShaper wands
    usage: /wand [area] [brush]

  pos:
    description: Sets the i'th position to your current position
    usage: /pos <index>

  set:
    description: Sets all blocks in the current area to the given pattern
    usage: /set <pattern>